apiVersion: v1
kind: Node
metadata:
  name: big-ip-cis-1
  annotations:
    #Replace MAC with your BIGIP Flannel VXLAN Tunnel MAC
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"42:01:0a:00:1e:03"}'
    flannel.alpha.coreos.com/backend-type: "vxlan"
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    #Replace IP with Self-IP for your deployment
    flannel.alpha.coreos.com/public-ip: "10.0.20.2"
spec:
  #Replace Subnet with your BIGIP Flannel Subnet
  podCIDR: "10.12.100.0/24"